title: Tech Begets Life 
author: Emmanuel Anene
email: eanene@gentzycode.com
description: > # this means to ignore newlines until "baseurl:"
  The tech ecosystem is evolving and the younger generation needs to leverage it. Tech begets life.

# social links
twitter_username: @tmannazy
github_username:  @tmannazy


show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
